********************************************************************************
* Title: Export STATA Results in Stata to external file.

/* Exports Models and required statistics in one table */

eststo clear
* Theory of Reasoned Action, Modified (ATTITUDE to DHUNT) (SEM Builder: TRAModif)
eststo: quietly /// /* Run model quietly and store */
sem (SUBNORM -> e1value e1diverse e1support e1livable, ) ///
	(SUBNORM -> INTENT, ) ///
	(ATTITUDE -> e3manage e3effort e3wilder e3overall, ) ///
	(ATTITUDE -> DHUNT, ) ///
	(ATTITUDE -> INTENT, ) ///
	(DHUNT -> a1hunted a2huntyrs a8travel a3pgame , ) ///
	(INTENT -> DHUNT, ) ///
	(INTENT -> a9altdist a7wtp c6interest , ), ///
	covstruct(_lexogenous, diagonal) ///
	latent(SUBNORM ATTITUDE DHUNT INTENT ) ///
	cov( SUBNORM*ATTITUDE) nocapslatent

* Theory of Reasoned Action with Moral Norms (SEM Builder: TRAMoral)
eststo: quietly ///
sem (SUBNORM -> e1value e1diverse e1support e1livable, ) ///
	(SUBNORM -> MORAL, ) ///
	(SUBNORM -> INTENT, ) ///
	(MORAL -> e2harvest e2respect e2maintain e2invest, ) ///
	(MORAL -> INTENT, ) ///
	(ATTITUDE -> MORAL, ) ///
	(ATTITUDE -> e3manage e3effort e3wilder e3overall, ) ///
	(ATTITUDE -> DHUNT, ) ///
	(ATTITUDE -> INTENT, ) ///
	(DHUNT -> a1hunted a2huntyrs a8travel a3pgame , ) ///
	(INTENT -> DHUNT, ) ///
	(INTENT -> a9altdist a7wtp c6interest, ), ///
	covstruct(_lexogenous, diagonal) ///
	latent(SUBNORM MORAL ATTITUDE DHUNT INTENT ) ///
	cov( SUBNORM*ATTITUDE) nocapslatent

esttab using TRA_TPB_se.rtf, wide onecell se replace /// 
star(* 0.10 ** 0.05) ///
nonumbers mtitle ("TRA" "TRA-moral" "TPB" "TPB-moral") ///
title ("Theory of Planned Behavior and Theory of Reasoned Action without and With Moral Norms") ///
addnote ("Data Source: PhD Dissertation Survey Data 2020.")

eststo clear

/*
Also Explore:

esttab, noisily notype
estout ,
 cells(b(fmt(a3) star) t(fmt(2) par("{ralign @modelwidth:{txt:(}" "{txt:)}}")))
 stats(N, fmt(%18.0g) labels(`"N"'))
 starlevels(* 0.05 ** 0.01 *** 0.001)
 varwidth(12)
 modelwidth(12)
 abbrev
 delimiter(" ")
 smcltags
 prehead(`"{hline @width}"')
 posthead("{hline @width}")
 prefoot("{hline @width}")
 postfoot(`"{hline @width}"' `"t statistics in parentheses"' `"@starlegend"')
 varlabels(, end("" "") nolast)
 mlabels(, depvar)
 numbers
 collabels(none)
 eqlabels(, begin("{hline @width}" "") nofirst)
 interaction(" # ")
 notype
 level(95)
 style(esttab)

return list

* More details on: http://repec.org/bocode/e/estout/esttab.html#esttab014
*/

/* Some Additional Notes */

/* 
UM2DOCX: Report Summary Statistics to DOCX files
13 Jul 2017, 22:33

sum2docx is now available on SSC, thanks to Prof. Kit Baum.
It makes reporting summary statistics easy to DOCX files, which can be easily appended to other docx files most likely to be generated by Stata 15 new command putdocx.
It can report all the statistics which can be reported by command summarize in detail model. You can specify those statistics as options.
Users can also append the output from sum2docx to other docx documents, which is more likely to be generated by putdocx, reg2docx and ect, either using the
append option or the command can be as following:

putdocx append d:/mytable0.docx d:/mytable1.docx d:/mytable2.docx, saving(d:/mytable.docx,replace)


Example


sysuse auto, clear

Report summary statistics for variable mpg weight length rep78 and foreign

sum2docx mpg weight length rep78 foreign using d:/temp1.docx, replace obs mean(%9.2f) sd min(%9.0g) median(%9.0g) max(%9.0g)

Add table tile

sum2docx mpg weight length rep78 foreign using d:/temp2.docx, replace obs mean sd min median max title("this is the summary statistics")

Add format for summary statistics

sum2docx mpg weight length rep78 foreign using d:/temp3.docx, replace obs mean(%9.2f) sd min(%9.0g) median(%9.0g) max(%9.0g) title("this is the
summary statistics")

Use wild card

sum2docx *n* m?g using d:/temp4.docx, replace obs mean(%9.2f) sd min(%9.0g) median(%9.0g) max(%9.0g) title("Table 1: this is the summary statistics")

Use all variables

drop make

sum2docx _all using d:/temp5.docx, replace obs mean(%9.2f) sd min(%9.0g) median(%9.0g) max(%9.0g) title("Table 1: this is the summary statistics")

Append all files together

putdocx append d:/temp1.docx d:/temp2.docx d:/temp3.docx d:/temp4.docx d:/temp5.docx, saving(d:/mytable.docx,replace)

We can also use the option append to append the output to an existing file

sum2docx mpg weight length rep78 foreign using d:/mytable.docx, append obs mean(%9.2f) sd min(%9.0g) median(%9.0g) max(%9.0g) title("this is the
summary statistics")

*/
